### ISSUE TITLE
Pool is not created using env variables

### ISSUE THREAD

**Issue by cblavier** [le0pard/redis_pool#1]
Hey,

I cannot manage to automatically create redis pool at application startup. Here is my application function in `mix.es`  :

```
def application do
  [
    applications: [:kernel, :stdlib, :logger, :inets, :ssl, :redis_pool],
    env: [pools: [tf_pool: [size: 12, max_overflow: 20, host: "127.0.0.1", port: 6379]]],
    mod: {TwitterFeelings, []}
  ]
end
```

My code is perfectly working if I run `RedisPool.create_pool(:tf_pool, 30, 'localhost', 6379)` manually during my application startup.

**Comment by le0pard** [comment]
Hello. I am not sure, what it is valid. Can you check in `iex -S mix` result of `Application.get_env(:redis_pool, :pools, [])` command?

**Comment by cblavier** [comment]
```
iex(1)> Application.get_env(:redis_pool, :pools, [])
[]
```

I guess I need to set env variables in `:redis_pool`  application context, but I'm unsure about how to do it

**Comment by le0pard** [comment]
Hello. I think it is not possible to setup `redis_pool` env inside another app in Elixir: http://elixir-lang.org/docs/master/elixir/Application.html

**Comment by cblavier** [comment]
Finally got it working :)

I added following line in `config/config.exs` : 

```
config :redis_pool, :pools, [tf_pool: [size: 10]]
```

Thanks for your help, it helped me to understand what wasn't working!

**Comment by le0pard** [comment]
Thanks! Can you do pull request in README about this?

**Comment by cblavier** [comment]
Sure, I will
