### ISSUE TITLE
App crashed and i have no idea why

### ISSUE THREAD

**Issue by jesteracer** [le0pard/redis_pool#4]
So I ran a phoenix app in production for some time and it crashed. Being new to elixir and erlang I cant understand what went wrong, but the erl crash dump points that the issue is with redis_pool. The first lines are:
=erl_crash_dump:0.3
Fri May  1 19:17:38 2015
Slogan: Kernel pid terminated (application_controller) ({application_terminated,redis_pool,shutdown})
System version: Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:false]
Compiled: Thu Apr  2 09:24:25 2015
Taints: crypto
Atoms: 10838
=memory
total: 23789624
processes: 8720856
processes_used: 8187352
system: 15068768
atom: 331249
atom_used: 303447
binary: 67616
code: 11227544
ets: 64264
=hash_table:atom_tab
size: 9643
used: 6551
objs: 10838
depth: 7 
...

It would be great if anyone could point me to the direction of were to dig.

**Comment by le0pard** [comment]
I don't have such problems with phoenix and redis_pool, maybe this will help with your problem: http://askubuntu.com/a/205566
